# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Update GithubPages
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v1

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
    
